swagger: "2.0"
info:
  title: "API"
  version: "1.0.0"

paths: {}

definitions:
  Resource:
    # Not a single required properties
    required: []
    properties:
      one:
        type: string
      two:
        type: string
      # Too long property name
      aTooLoooooooooooooooooooooooooooooooooongPropertyName:
        type: string
  AnotherResource:
    # One required properties
    required:
      - one
    properties:
      one:
        type: string
      two:
        type: string