swagger: "2.0"
info:
  title: "API"
  version: "1.0.0"
paths: {}

definitions:
  # Valid
  ValidSchemaName:
    required:
      - aProperty
    properties:
      aProperty:
        type: string
  # Not in UpperCamelCase
  invalidSchemaName:
    required:
      - aProperty
    properties:
      aProperty:
        type: string
  # Ends with invalid tech suffix: should trigger schema-name-is-valid-not-working but is not :-(
  InvalidSchemaNameDto:
    required:
      - aProperty
    properties:
      aProperty:
        type: string