swagger: "2.0"
info:
  title: "API"
  version: "1.0.0"
paths:
  /resources:
    delete:
      summary: Delete all resources
      responses:
        '204':
          description: Done
  /some-resources:
    delete:
      summary: Delete all resources
      responses:
        '201':
          description: Resources deleted 
        '500':
          description: Oops
  /some-other-resources:
    delete:
      summary: Delete all resources
      responses:
        '200':
          description: Resources deleted 
        '400':
          description: Error