rules:
  authorized-http-methods:
    summary: Only post, get, put, patch and delete HTTP methods are allowed
    severity: 0
    tags:
      - http method
    given: $.paths.*
    then:
      field: "@key"
      function: pattern
      functionOptions:
        match: ^(parameters|x-.*|post|get|put|patch|delete)$
    
  expected-http-status-all-methods-errors:
    summary: Operation must at least return a 401 and a 500 error HTTP status codes
    severity: 0
    tags:
      - http status
    given: $.paths.*.*.responses
    then:
      - field: "401"
        function: truthy
      - field: "500"
        function: truthy

  expected-http-status-all-methods-successes:
    # source: https://github.com/stoplightio/spectral/blob/master/src/rulesets/oas/ruleset.json
    summary: Operation must have at least one `2xx` response.
    severity: 0
    tags:
      - http status
    given: $..paths.*[?( name() === 'get' || name() === 'put' || name() === 'post' || name() === 'delete' || name() === 'options' || name() === 'head' || name() === 'patch' || name() === 'trace' )]
    then:
      field: responses
      function: oasOp2xxResponse