# ruleset for spectral version 4.x.x (tested with 4.2.0)
extends: [[spectral:oas2, off]]
rules:
  

  # Security
  security-definitions-defined:
    recommended: true
    description: Security definitions must be defined
    severity: error
    tags:
      - security
    given: $
    then:
      field: securityDefinitions
      function: truthy
      
  security-definitions-authorized:
    recommended: true
    description: Only apiKey and oauth security definitions are allowed
    severity: error
    tags:
      - security
    given: $.securityDefinitions.*
    then:
      field: type
      function: enumeration
      functionOptions:
        values:
          - apiKey
          - oauth2

  security-definitions-oauth-scopes-defined:
    recommended: true
    description: Scopes must be defined for all Oauth2 security definitions
    severity: error
    tags:
      - security
    given: $.securityDefinitions[?(@.type==='oauth2')]
    then:
      field: scopes
      function: truthy

  security-no-api-level:
    recommended: true
    description: API level security is forbidden (must be configured at operation level)
    severity: error
    tags:
      - security
    given: $
    then:
      field: security
      function: falsy
  
  security-operation-defined:
    recommended: true
    description: Security must be defined on each operation
    severity: error
    tags:
      - security
    given: $.paths.*.*
    then:
      field: security
      function: truthy
  # Rules ideas:
  # ------------
  # no schema on 204
  # no known bad prefix or suffix on midfix in property dte for example