swagger: "2.0"
info:
  title: "API"
  version: "1.0.0"
paths:
  /resources:
    get:
      summary: Gets some resources
      responses:
        '200':
          description: Resources
        '401':
          description: Unauthorized
        '500':
          description: Unexpected error
    options: # Error
      summary: Lists available HTTP methods
      responses:
        '200':
          description: available http methods
          schema:
            type: string
        '401':
          description: Unauthorized
        '500':
          description: Unexpected error
    head: # Error
      summary: Headers
      responses:
        '200':
          description: only headers
        '401':
          description: Unauthorized
        '500':
          description: Unexpected error
    delete:
      summary: Delete all resources
      responses:
        '204':
          description: Done
        '401':
          description: Unauthorized
        '500':
          description: Unexpected error
  /other-resources:
    get:
      summary: Gets some resources
      responses:
        '200':
          description: Resources
        '401':
          description: Unauthorized
        '500':
          description: Unexpected error
    options: # Error
      summary: Lists available HTTP methods
      responses:
        '200':
          description: available http methods
          schema:
            type: string
        '401':
          description: Unauthorized
        '500':
          description: Unexpected error