swagger: "2.0"
info:
  title: "API"
  version: "1.0.0"
paths:
  /resources:
    get:
      summary: Lists available HTTP methods
      responses: # Error x 2 (missing 401 and 500)
        '201':
          description: available http methods
          schema:
            type: string
    delete:
      summary: Delete all resources
      responses: # Error (missing 500)
        '200':
          description: Done
        '401':
          description: Unauthorized
  /other-resources:
    get:
      summary: Lists available HTTP methods
      responses: # Error x 2 (missing 401 and 500)
        '201':
          description: available http methods
          schema:
            type: string
    delete:
      summary: Delete all resources
      responses:
        '200':
          description: Done
        '401':
          description: Unauthorized
        '500':
          description: Unexpected error
