swagger: "2.0"
info:
  title: "API"
  version: "1.0.0"
paths:
  /resources:
    get:
      responses:
        '200':
          description: Resources
        '401':
          description: Unauthorized
        '500':
          description: Unexpected error
    delete:
      summary: Lists available HTTP methods
      responses: # Error (missing 2XX)
        '401':
          description: Unauthorized
        '500':
          description: Unexpected error
  /other-resources:
    get:
      responses: # Error (missing 2XX)
        '401':
          description: Unauthorized
        '500':
          description: Unexpected error
    delete:
      responses:
        '204':
          description: Deleted
          schema:
            type: string
        '401':
          description: Unauthorized
        '500':
          description: Unexpected error