swagger: "2.0"
info:
  title: "API"
  version: "1.0.0"
paths:
  /resources:
    parameters:
      - name: type
        in: query
        type: string
    delete:
      summary: deletes some resources
      responses:
        204:
          description: Resources deleted
  /errorResources?type={type}:
    parameters:
      - name: type
        in: query
        type: string
    delete:
      summary: deletes some resources
      responses:
        204:
          description: Resources deleted