swagger: "2.0"
info:
  title: "API"
  version: "1.0.0"
paths:
  /resources:
    get:
      summary: Lists resources
      parameters:
        - name: q
          in: query
          type: string
      responses: 
        '200':
          description: Success
          schema:
            properties:
              data:
                type: string
        '401':
          description: Unauthorized
        '500':
          description: Unexpected error
  /other-resources:
    post:
      summary: Lists resources
      parameters:
        - name: q
          in: query
          type: string
      responses:
        '201':
          description: Success
          schema:
            properties:
              data:
                type: string
        '401':
          description: Unauthorized
        '500':
          description: Unexpected error
