swagger: "2.0"
info:
  title: "API"
  version: "1.0.0"
paths: {}

definitions:
  ValidSchemaName:
    required:
      - aProperty
    properties:
      aProperty:
        type: string
  invalidSchemaName:
    required:
      - aProperty
    properties:
      aProperty:
        type: string
  InvalidSchemaNameDto:
    required:
      - aProperty
    properties:
      aProperty:
        type: string