swagger: "2.0"
info:
  title: "API"
  version: "1.0.0"

securityDefinitions:
  someApiKey:
    type: apiKeye
    in: header
    name: DA_API_KEY
  someOauth:
    type: oauth2
    flow: accessCode
    scopes:
      admin: Admin scope
      user: User scope
      media: Media scope
  someOauthWithoutScopes:
    type: oauth2
    flow: accessCode

security:
  - someApiKey: []

paths:

  /resources:
    get:
      responses:
        204:
          description: nothing
  /otherResources:
    post:
      responses:
        201:
          description: Created
          schema:
            $ref: "#/definitions/OtherResource"
    get:
      security:
        someOauth:
          - user
      responses:
        200:
          description: OK
          schema:
            type: string
        500:
          description: something went wrong
          schema:
            $ref: "#/definitions/Error"

definitions:
  Error:
    properties:
      messageuh:
        type: string
  OtherResource:
    type: string