swagger: "2.0"
info:
  title: "API"
  version: "1.0.0"

paths:
  /resources:
    post:
      parameters:
        - name: bodyParameterOnPost
          in: body
          type: string
      responses:
        '202':
          description: Created
    delete:
      parameters:
        - name: bodyParameterOnDelete 
          in: body # Error (body on delete)
          type: string
        - name: anotherParameter
          in: query
          type: string
      responses:
        '204':
          description: Resources deleted