swagger: "2.0"
info:
  title: "API"
  version: "1.0.0"
paths:
  /withoutGetResources:
    post:
      summary: Creates something
      responses:
        '201':
          description: created
          schema:
            required:
              - id
            properties:
              id:
                type: string      
  /resources:
    post:
      summary: creates some /resources
      responses:
        '201':
          description: created
          schema:
            required:
              - id
            properties:
              id:
                type: string
    get:
      responses:
        '200':
          description: search results
          schema:
            properties:
              items:
                type: array
                items:
                  properties:
                    someAttribute:
                      type: string
  /v1/paginatedResources:
    get:
      responses:
        '200':
          description: search results
          schema:
            properties:
              page:
                properties:
                  pageSize:
                    type: number
                  pageNumber:
                    type: number
                  totalElements:
                    type: number
                  totalPages:
                    type: number
                  before:
                    type: string
                  after: 
                    type: string
              items:
                type: array
                items:
                  properties:
                    someAttribute:
                      type: string
  /additionalInformationResources:
    get:
      responses:
        '200':
          description: search results
          schema:
            properties:
              additionalInformation:
                properties: 
                  someHighLevelProperty:
                    type: number
              items:
                type: array
                items:
                  properties:
                    someAttribute:
                      type: string
  /errorPaginatedResources: # Error page does not match schema
    get:
      responses:
        '200':
          description: search results
          schema:
            properties:
              page:
                properties:
                  size:
                    type: number
              items:
                type: array
                items:
                  properties:
                    someAttribute:
                      type: string

  /v2/resources/{someId}/errorStringArrayResources: # Error response is not an array (also trigger "response-only-object") -> OK
    get:
      parameters:
        - name: someId
          type: string
          required: true
          in: path
      responses:
        '200':
          description: search results
          schema:
            type: array
            items:
              type: string
  /v1/errorItemsStringArrayResources: # Error: items is an array of string instead of objects -> OK
    get:
      responses:
        '200':
          description: search results
          schema:
            properties:
              items:
                type: array
                items:
                  type: string
  /resources/{someId}/errorNoItemsResources: # Error: the list is named resources instead of items -> OK
    get:
      parameters:
        - name: someId
          type: string
          required: true
          in: path
      responses:
        '200':
          description: wrong schema
          schema:
            properties:
              resources:
                type: array
                items:
                  properties:
                    someAttribute:
                      type: string
  /resources/{someId}-{anotherId}/errorRootDataResources: # Error: data at root level (outside of additionalInformation) -> OK
    get:
      parameters:
        - name: someId
          type: string
          required: true
          in: path
      parameters:
        - name: anotherId
          type: string
          required: true
          in: path
      responses:
        '200':
          description: search results
          schema:
            properties:
              totalCount:
                type: number
              items:
                type: array
                items:
                  properties:
                    someAttribute:
                      type: string
  /resources/{someId}/otherResources/{anotherId}/errorEmpryAdditionalInformationResources: # Error : empty additionalInformation -> OK
    get:
      parameters:
        - name: someId
          type: string
          required: true
          in: path
      parameters:
        - name: anotherId
          type: string
          required: true
          in: path
      responses:
        '200':
          description: search results
          schema:
            properties:
              additionalInformation:
                type: object
              items:
                type: array
                items:
                  properties:
                    someAttribute:
                      type: string
