swagger: "2.0"
info:
  title: "API"
  version: "1.0.0"
paths:
  /resources:
    get:
      responses:
        '200':
          description: search results
          schema:
            properties:
              items:
                type: array
                items:
                  properties:
                    someAttribute:
                      type: string
  /resourcesWithPagination:
    get:
      responses:
        '200':
          description: search results
          schema:
            properties:
              page:
                properties:
                  pageSize:
                    type: number
                  pageNumber:
                    type: number
                  totalElements:
                    type: number
                  totalPages:
                    type: number
                  before:
                    type: string
                  after: 
                    type: string
              items:
                type: array
                items:
                  properties:
                    someAttribute:
                      type: string
  /resourcesWithAdditionInformation:
    get:
      responses:
        '200':
          description: search results
          schema:
            properties:
              additionalInformation:
                properties: 
                  someHighLevelProperty:
                    type: number
              items:
                type: array
                items:
                  properties:
                    someAttribute:
                      type: string
  /resourcesWithWrongPagination: # Error page does not match schema
    get:
      responses:
        '200':
          description: search results
          schema:
            properties:
              page:
                properties:
                  size:
                    type: number
              items:
                type: array
                items:
                  properties:
                    someAttribute:
                      type: string

  /resourcesStringArray: # Error response is not an array (also trigger "response-only-object") -> OK
    get:
      responses:
        '200':
          description: search results
          schema:
            type: array
            items:
              type: string
  /resourcesWithWrongArrayType: # Error: items is an array of string instead of objects -> OK
    get:
      responses:
        '200':
          description: search results
          schema:
            properties:
              items:
                type: array
                items:
                  type: string
  /resourcesWithWrongArrayName: # Error: the list is named resources instead of items -> OK
    get:
      responses:
        '200':
          description: wrong schema
          schema:
            properties:
              resources:
                type: array
                items:
                  properties:
                    someAttribute:
                      type: string
  /resourcesWithForbiddenRootData: # Error: data at root level (outside of additionalInformation) -> OK
    get:
      responses:
        '200':
          description: search results
          schema:
            properties:
              totalCount:
                type: number
              items:
                type: array
                items:
                  properties:
                    someAttribute:
                      type: string
  /resourcesWithEmptyAdditionalInformation: # Error : empty additionalInformation -> OK
    get:
      responses:
        '200':
          description: search results
          schema:
            properties:
              additionalInformation:
                type: object
              items:
                type: array
                items:
                  properties:
                    someAttribute:
                      type: string
