swagger: "2.0"
info:
  title: "API"
  version: "1.0.0"
parameters:
  dummyPathParameter:
    name: dummyPathParameter
    in: path
    type: string
    required: true
  InvalidDummyPathParameter:
    name: DummyPathParameter
    in: path
    type: string
    required: true
  dummyQueryParameter:
    name: dummyPathParameter
    in: query
    type: string
  InvalidDummyQueryParameter:
    name: DummyPathParameter
    in: query
    type: string
  dummyHeader:
    name: DUMMY-HEADER
    in: header
    type: string

paths:
  /resources:
    delete:
      parameters:
        - name: SomeParameter # Error (not lowerCamelCase)
          in: query
          type: string
        - name: anotherParameter
          in: query
          type: string
      responses:
        '204':
          description: Resources deleted
  /resources/{ResourceId}:
    parameters:
      - name: ResourceId # Error (not lowerCamelCase)
        in: path
        type: string
        required: true
      - name: 'Some-Header' # Not checked because not in query or path
        in: header
        type: string
        required: false
    delete:
      responses:
        '204':
          description: Resource deleted