swagger: "2.0"
info:
  title: "API"
  version: "1.0.0"
paths:
  /resources/: # Error (trailing slash)
    get:
      summary: Lists resources
      responses: 
        '200':
          description: The resources
          schema:
            type: string
        '401':
          description: Unauthorized
        '500':
          description: Unexpected error
  /other-resources:
    get:
      summary: Lists resources
      responses:
        '200':
          description: The resources
          schema:
            type: string
        '401':
          description: Unauthorized
        '500':
          description: Unexpected error
