swagger: "2.0"
info:
  title: "API"
  version: "1.0.0"
paths:
  /strings:
    get:
      summary: Lists resources
      responses: 
        '200':
          description: The resources
          schema:
            type: string
        '401':
          description: Unauthorized
          schema:
            $ref: "#/definitions/ErrorObject"
        '500':
          description: Unexpected error
          schema:
            $ref: "#/definitions/ErrorString"
    delete:
      summary: deletes some resources
      responses: 
        '204':
          description: Deleted
        '401':
          description: Unauthorized
          schema:
            $ref: "#/definitions/ErrorObject"
        '500':
          description: Unexpected error
          schema:
            $ref: "#/definitions/ErrorString"
  /arrays:
    get:
      summary: Lists resources
      responses:
        '200':
          description: The resources
          schema:
            type: array
            items:
              type: string
        '401':
          description: Unauthorized
          schema: 
            properties:
              message:
                type: string
        '500':
          description: Unexpected error
  /objects:
    get:
      summary: Lists resources
      responses:
        '200':
          description: The resources
          schema:
            properties:
              aProperty:
                type: string
        '401':
          description: Unauthorized
          schema: 
            properties:
              message:
                type: string
        '500':
          description: Unexpected error
definitions:
  ErrorString:
    type: string
  ErrorObject:
    properties:
      message:
        type: string