swagger: "2.0"
info:
  title: "API"
  version: "1.0.0"
paths:
  /badErrors:
    delete:
      responses:
        '204':
          description: Deleted
        '401':
          description: Unauthorized
          # Totally invalid schema (paths./badErrors.delete.responses.401.schema.properties)
          schema:
            required:
              - message
            properties:
              message:
                type: string
        '403':
          description: Forbidden
          schema:
            required:
              - errors
            properties:
              errors:
                type: array
                minItems: 1
                items:
                  # Missing 'code' in required (paths./badErrors.delete.responses.403.schema.properties.items)
                  required:
                    - message
                  properties:
                    code:
                      type: string
                      description: le code de l'erreur
                      example: INVALID_FORMAT
                    message:
                      type: string
                      description: description de l'erreur
                      example: Invalid format
                    attribute:
                      type: string
                      description: nom de l'attribut source de l'erreur
                      example: zip
                    path:
                      type: string
                      description: JSON path de l'attribut en erreur
                      example: $.addresses[2].zip
                    additionalInformation:
                      description: propriétés additionnelles spécifiques, à compléter ou supprimer selon les besoins
                      type: object
                      properties:
                        additionPropertyExample:
                          type: string
        '404':
          description: Not found error
          schema:
            required:
              - errors
            properties:
              errors:
                type: array
                minItems: 1
                items:
                  required:
                    - code
                    - message
                  properties:
                    code:
                      type: string
                      description: le code de l'erreur
                      example: INVALID_FORMAT
                    message:
                      type: string
                      description: description de l'erreur
                      example: Invalid format
                  # Undocumented additional information: forbidden!
                    additionalInformation:
                      description: propriétés additionnelles spécifiques, à compléter ou supprimer selon les besoins
                      type: object

        '500':
          description: Unexpected error
          schema:
            required:
              - errors
            properties:
              # Error! En error response can only contain errors, nothing else (paths./badErrors.delete.responses.500.schema.properties)
              forbiddenAdditionalProperty:
                type: string
              errors:
                type: array
                minItems: 1
                items:
                  required:
                    - code
                    - message
                  properties:
                    code:
                      type: string
                      description: le code de l'erreur
                      example: INVALID_FORMAT
                    message:
                      type: string
                      description: description de l'erreur
                      example: Invalid format
                    attribute:
                      type: string
                      description: nom de l'attribut source de l'erreur
                      example: zip
                    path:
                      type: string
                      description: JSON path de l'attribut en erreur
                      example: $.addresses[2].zip
                    additionalInformation:
                      description: propriétés additionnelles spécifiques, à compléter ou supprimer selon les besoins
                      type: object
                      properties:
                        additionPropertyExample:
                          type: string
    
  /goodErrors:
    delete:
      responses:
        '204':
          description: Deleted
        '401':
          description: Unauthorized
          # Valid and complete errors schema
          schema:
            required:
              - errors
            properties:
              errors:
                type: array
                minItems: 1
                items:
                  required:
                    - code
                    - message
                  properties:
                    code:
                      type: string
                      description: le code de l'erreur
                      example: INVALID_FORMAT
                    message:
                      type: string
                      description: description de l'erreur
                      example: Invalid format
                    attribute:
                      type: string
                      description: nom de l'attribut source de l'erreur
                      example: zip
                    path:
                      type: string
                      description: JSON path de l'attribut en erreur
                      example: $.addresses[2].zip
                    additionalInformation:
                      description: propriétés additionnelles spécifiques, à compléter ou supprimer selon les besoins
                      type: object
                      properties:
                        additionPropertyExample:
                          type: string
        '403':
          description: Forbidden
          # Valid and partial errors schema
          schema:
            required:
              - errors
            properties:
              errors:
                type: array
                minItems: 1
                items:
                  required:
                    - code
                    - message
                  properties:
                    code:
                      type: string
                      description: le code de l'erreur
                      example: INVALID_FORMAT
                    message:
                      type: string
                      description: description de l'erreur
                      example: Invalid format        
        '500':
          description: Unexpected error
          schema:
            required:
              - errors
            properties:
              errors:
                type: array
                minItems: 1
                items:
                  required:
                    - code
                    - message
                  properties:
                    code:
                      type: string
                      description: le code de l'erreur
                      example: INVALID_FORMAT
                    message:
                      type: string
                      description: description de l'erreur
                      example: Invalid format
                    attribute:
                      type: string
                      description: nom de l'attribut source de l'erreur
                      example: zip
                    path:
                      type: string
                      description: JSON path de l'attribut en erreur
                      example: $.addresses[2].zip
