swagger: "2.0"
info:
  title: "API"
  version: "1.0.0"
paths:
  /badErrors:
    delete:
      responses:
        '204':
          description: Deleted
        '401':
          description: Unauthorized
          schema:
            required:
              - message
            properties:
              message:
                type: string
              
        '500':
          description: Unexpected error
          schema:
            required:
              - message
            properties:
              message:
                type: string
    
  /goodErrors:
    delete:
      responses:
        '204':
          description: Deleted
        '401':
          description: Unauthorized
          # Valid and complete errors schema
          schema:
            required:
              - errors
            properties:
              errors:
                type: array
                minItems: 1
                items:
                  required:
                    - code
                    - message
                  properties:
                    code:
                      type: string
                      description: le code de l'erreur
                      example: INVALID_FORMAT
                    message:
                      type: string
                      description: description de l'erreur
                      example: Invalid format
                    attribute:
                      type: string
                      description: nom de l'attribut source de l'erreur
                      example: zip
                    path:
                      type: string
                      description: JSON path de l'attribut en erreur
                      example: $.addresses[2].zip
                    additionalInformation:
                      description: propriétés additionnelles spécifiques, à compléter ou supprimer selon les besoins
                      type: object
                      example:
                        regex: "[0-9]{5}"
        '403':
          description: Forbidden
          # Valid and partial errors schema
          schema:
            required:
              - errors
            properties:
              errors:
                type: array
                minItems: 1
                items:
                  required:
                    - code
                    - message
                  properties:
                    code:
                      type: string
                      description: le code de l'erreur
                      example: INVALID_FORMAT
                    message:
                      type: string
                      description: description de l'erreur
                      example: Invalid format        
        '500':
          description: Unexpected error
          schema:
            required:
              - errors
            properties:
              invalidAdditionalProperty:
                type: string
              errors:
                type: array
                minItems: 1
                items:
                  required:
                    - code
                    - message
                  properties:
                    code:
                      type: string
                      description: le code de l'erreur
                      example: INVALID_FORMAT
                    message:
                      type: string
                      description: description de l'erreur
                      example: Invalid format
                    attribute:
                      type: string
                      description: nom de l'attribut source de l'erreur
                      example: zip
                    path:
                      type: string
                      description: JSON path de l'attribut en erreur
                      example: $.addresses[2].zip
                    additionalInformation:
                      description: propriétés additionnelles spécifiques, à compléter ou supprimer selon les besoins
                      type: object
                      example:
                        regex: "[0-9]{5}"