swagger: "2.0"
info:
  title: "API"
  version: "1.0.0"
paths:
  /resources: # Error (trailing slash)
    get:
      summary: Lists resources
      responses: 
        '200':
          description: The resources
          schema:
            type: string
        '401':
          description: Unauthorized
          schema:
            $ref: "#/definitions/ErrorObject"
        '500':
          description: Unexpected error
          schema:
            $ref: "#/definitions/ErrorString"
  /other-resources:
    get:
      summary: Lists resources
      responses:
        '200':
          description: The resources
          schema:
            type: string
        '401':
          description: Unauthorized
          schema: 
            properties:
              message:
                type: string
        '500':
          description: Unexpected error

definitions:
  ErrorString:
    type: string
  ErrorObject:
    properties:
      message:
        type: string