swagger: "2.0"
info:
  title: "API"
  version: "1.0.0"
paths:
  /resources:
    get:
      summary: Lists resources
      parameters:
        - name: q
          in: query
          type: string
      responses: 
        '200':
          description: Success
          schema:
            properties:
              data:
                type: string
        '401':
          description: Unauthorized
        '500':
          description: Unexpected error
  /other-resources:
    post:
      summary: Do something
      parameters:
        - name: body
          in: body
          schema:
            properties:
              data:
                type: string
      responses:
        '201':
          description: Success
          schema:
            properties:
              data:
                type: string
        '401':
          description: Unauthorized
          schema:
            required:
              - code
            properties:
              code:
                type: string
              message:
                type: string
        '500':
          description: Unexpected error
          schema:
            properties:
              code:
                type: string
              message:
                type: string
definitions:
  SomeSchema:
    required:
      - aProperty
    properties:
      aProperty:
        type: string
      anotherProperty:
        type: string
  SomeSuspiciousSchema: # Info: no required?
    properties:
      aProperty:
        type: string
      anotherProperty:
        type: string
  AnotherSuspiciousSchema: # Info: no required?
    required: []
    properties:
      aProperty:
        type: string
      anotherProperty:
        type: string